### ISSUE TITLE
Cardano data collection query fails

### ISSUE THREAD

**Issue by dimkarakostas** [Blockchain-Technology-Lab/tokenomics-decentralization#62]
Error raised: `Forbidden('Access Denied: Table iog-data-analytics:cardano_mainnet.block: User does not have permission to query table iog-data-analytics:cardano_mainnet.block, or perhaps it does not exist in location US.')`

**Comment by HHobeck** [comment]
@dimkarakostas Can you please give some background information what this ticket is about? How did you find the problem and how does it affects the EDI dashboard? Is this error the reason why Cardano is not shown in the EDI dashboard since March 2023?

**Comment by dimkarakostas** [comment]
@HHobeck The bigquery project `iog-data-analytics.cardano_mainnet` was discontinued around that time and was replaced by `blockchain-analytics-392322.cardano_mainnet`. However, the new dataset doesn't offer the view `vw_tx_in_out_with_inputs_value`, which was in the original dataset and was used by the data collection query in this repo. So the query needs to be rewritten to use the new dataset, in order to get latest data.

**Comment by HHobeck** [comment]
Thank you for the explanation. I think this topic is very important because of multiple reason and we should fix this as soon as possible.

It should be feasible to change API calls and use the new DTO structure, right? Or do you see any conceptual problems? Is there anyone active in development?

**Comment by LadyChristina** [comment]
@HHobeck We recently started running our own Cardano node at the lab, so the current plan is to switch to using the data from there instead of BigQuery. A member of our team is currently looking into making this transition, so hopefully it will be ready soon.

**Comment by HHobeck** [comment]
Please give this topic high priority. The current situation is unbearable.

**Comment by dimkarakostas** [comment]
@HHobeck Please feel free to look into the current BigQuery dataset that I mentioned above and craft a query to get the latest tokenomics data, if you are in a hurry. We'll be happy to merge your solution in this repository, so as to have up-to-date data until we switch to the Cardano node.

**Comment by HHobeck** [comment]
> @HHobeck Please feel free to look into the current BigQuery dataset that I mentioned above and craft a query to get the latest tokenomics data, if you are in a hurry. We'll be happy to merge your solution in this repository, so as to have up-to-date data until we switch to the Cardano node.

Yes no problem. I can give it a try and take a look into it. Could you give me an outlook? Approximately how long does it take to implement the Cardano node on your site? (just to have feeling if it is worth building a short-term solution)

**Comment by LadyChristina** [comment]
@HHobeck We estimate it will take about a month, given our current workload, so it should be ready and integrated in the dashboard by the beginning of November.
